<a href="https://colab.research.google.com/github/Anamika79/MLDLS2021/blob/main/Glass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('glass.csv')
print(dataset)

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]


In [3]:
X = dataset.iloc[:,0:8].values
Y = dataset.iloc[:,-1].values

In [4]:
print(X.shape, Y.shape)

(214, 8) (214,)


In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)
print(X_train.shape, X_test.shape)

(171, 8) (43, 8)


In [6]:
#Logistic Regression

from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()
logReg.fit(X_train, Y_train)

Y_pred = logReg.predict(X_test)
print(Y_test, Y_pred)

[3 2 2 2 1 3 1 2 2 3 5 2 1 2 1 1 1 1 2 2 2 1 5 2 3 7 3 2 1 1 2 1 1 3 7 7 1
 6 2 2 1 2 1] [1 5 2 2 1 1 2 2 2 2 7 2 1 2 1 1 2 1 2 1 2 2 2 2 2 7 2 1 1 1 1 1 1 1 7 7 2
 2 5 2 2 2 1]


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [7]:
from sklearn.metrics import  confusion_matrix, accuracy_score, precision_score, recall_score

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred)) 
print("Precision:\n", precision_score(Y_test, Y_pred, average=None))
print("Recall:\n", recall_score(Y_test, Y_pred, average = None))

Confusion Matrix:
 [[10  5  0  0  0  0]
 [ 3 11  0  2  0  0]
 [ 3  3  0  0  0  0]
 [ 0  1  0  0  0  1]
 [ 0  1  0  0  0  0]
 [ 0  0  0  0  0  3]]
Accuracy:
 0.5581395348837209
Precision:
 [0.625      0.52380952 0.         0.         0.         0.75      ]
Recall:
 [0.66666667 0.6875     0.         0.         0.         1.        ]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
#KNN Classifier

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)

Y_pred_knn = knn.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_knn))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_knn)) 

Confusion Matrix:
 [[13  2  0  0  0  0]
 [ 4 12  0  0  0  0]
 [ 6  0  0  0  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  3]]
Accuracy:
 0.6744186046511628


In [9]:
#Decision Tree
from sklearn.tree import DecisionTreeClassifier

dtc= DecisionTreeClassifier()
dtc.fit(X_train, Y_train)

Y_pred_dtc = dtc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_dtc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_dtc)) 

Confusion Matrix:
 [[10  2  1  0  1  1]
 [ 3 12  0  0  0  1]
 [ 2  1  3  0  0  0]
 [ 0  0  0  1  0  1]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  3]]
Accuracy:
 0.6976744186046512


In [10]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()
rfc.fit(X_train, Y_train)

Y_pred_rfc = rfc.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_rfc))
print("Accuracy:\n", accuracy_score(Y_test, Y_pred_rfc))

Confusion Matrix:
 [[13  2  0  0  0  0]
 [ 1 14  0  0  0  1]
 [ 3  3  0  0  0  0]
 [ 0  1  0  0  0  1]
 [ 0  0  0  0  1  0]
 [ 0  0  0  0  0  3]]
Accuracy:
 0.7209302325581395
